name: widget-server pipe DockerHub

on: 
  push:
    braches: 
      - 'main'

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      
      - name: Login to DocjerHub
        id: login-docker-DocjerHubuses:docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN}}

      - name: Generate tag
        id: generate_tag
        # GITHUB_SHA - get commit hash
        # $GITHUB_SHA | head -c7 - get only the first 7 characters of the commit hash
        # "sha=$SHA" >> $GITHUB_OUTPUT - store the value of $SHA in the sha variable and put it in the github output
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build and push image to AWS ECR
        id: build-push-image
        env:
          DOCKERHUB_REPOSITORY: ${{ vars.DOCKERHUB_REPOSITORY }}
          IMAGE_TAG: ${{ steps.generate_tag.outputs.sha }}
        run: |
          docker build -t $DOCKERHUB_REPOSITORY:$IMAGE_TAG .
          docker push $DOCKERHUB_REPOSITORY:$IMAGE_TAG